version: '3.1'

services:   
    
  db:
    container_name: 'db_icone_virtual'
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=db_icone_virtual_docker
    ports:
      - "3306:3306"
    volumes:
      - ./src/database:/app/api

  app:
    build: .
    container_name: 'api_icone_virtual'          
    depends_on:
      - db          
    environment:
     DB_HOST: db
     DB_USERNAME: root
     DB_PASSWORD: 123
     DB_DATABASE: db_icone_virtual_docker
     DB_PORT: 3306
     WAIT_HOSTS: db:3306
    volumes:
      - .:/src/    

   
