version: '3'

services:
  db:
    container_name: 'db_icone_virtual_docker'
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3306:3306"
    networks:
      - icone-virtual-network

  app:
    build: .
    container_name: 'api_icone_virtual'

    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    ports:
      - "3333:3333"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - icone-virtual-network

networks:
  icone-virtual-network:
    driver: bridge
